import Head from 'next/head'
import Banner from '../components/Banner'
import Nav from '../components/Nav'
import ProductsFeed from '../components/ProductsFeed'
import React from 'react'


export default function Home({ products }: any) {
  return (
    <div className='bg-gray-100'>
      <Head>
        <title>Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className='max-w-screen'>
        <Banner />
        <ProductsFeed products={products}/>
      </main>
    </div>
  )
}

export async function getServerSideProps(context: any) {
  const products = await fetch('https://fakestoreapi.com/products').then(res=>res.json())
  return {
    props: {
      products
    }, // will be passed to the page component as props
  }
}